[general]
bios_path = "bios.bin"
bios_skip = false
sync_to_audio = false

[cartridge]
# Possible values: detect, none, sram, flash64, flash128, eeprom512, eeprom8192
save_type = "detect"
# Force-enable RTC emulation, otherwise rely on game database.
force_rtc = true

[video]
fullscreen = false
scale = 2
# Set empty string for no shader.
shader_vs = "shader/gba_colors.vs"
shader_fs = "shader/gba_colors.fs"

[audio]
# Possible values: cosine, cubic, sinc64, sinc128, sinc256
resampler = "cubic"
# Filter FIFO audio before passing it to the mixer.
# This will reduce the dity high-frequency aliasing typical to the GBA.
interpolate_fifo = true
# Reimplementation of the popular MP2K/M4A audio mixer with higher quality.
# This is experimental and may still have issues.
mp2k_hle_enable = false
# Use cubic interpolation in the MP2K reimplementation.
mp2k_hle_cubic = false 