[general]
bios_path = "bios.bin"
bios_skip = false

[cartridge]
# Possible values: detect, none, sram, flash64, flash128, eeprom512, eeprom8192
save_type = "detect"
# Force-enable RTC emulation, otherwise rely on game database.
force_rtc = true
# Force-enable Solar Sensor emulation, otherwise rely on game database.
force_solar_sensor = false
# Solar Sensor light intensity (0 = lowest intensity, 255 = highest intensity)
solar_sensor_level = 23

[video]
filter = "linear"
color_correction = "agb"
lcd_ghosting = true

[audio]
# Possible values: cosine, cubic, sinc64, sinc128, sinc256
resampler = "cubic"
# Filter FIFO audio before passing it to the mixer.
# This will reduce the dity high-frequency aliasing typical to the GBA.
interpolate_fifo = false
# Reimplementation of the popular MP2K/M4A audio mixer with higher quality.
# This is experimental and may still have issues.
mp2k_hle_enable = false
# Use cubic interpolation in the MP2K reimplementation.
mp2k_hle_cubic = false 

[input]
fast_forward = [32, -1, 4]
hold_fast_forward = true
controller_guid = ""
[input.gba]
b = [83, 1, -1]
a = [65, 0, -1]
select = [16777219, 4, -1]
right = [16777236, 14, 0]
r = [70, 10, -1]
l = [68, 9, -1]
left = [16777234, 13, 128]
start = [16777220, 6, -1]
down = [16777237, 12, 1]
up = [16777235, 11, 129]

[window]
fullscreen = false
fullscreen_show_menu = false
scale = 2
# Set to zero to unlock the scale
maximum_scale = 0
# Show the current frames per second in the window title
show_fps = false
# Lock the screen to a 3:2 aspect ratio
lock_aspect_ratio = true
# Snap screen size to integer multiples of the original screen width and height
snap_to_integer_scale = false
